services:
  postgres:
    image: postgres:16.6-alpine3.21
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pgpass
    configs:
      - source: init.sql
        target: /docker-entrypoint-initdb.d/init.sql

configs:
  init.sql:
    content: |
      CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
